name: "Upload to last release"
description: "Upload an asset to the last release"
author: "Planet Code"
inputs:
  token:
    description: "The Github token"
    required: true
  asset-path:
    description: The path to the asset to upload"
    required: true
  asset-name:
    description: "The name of the asset"
    required: true
    default: "artifact.zip"
runs:
  using: "node12"
  main: "dist/index.js"
